### ISSUE TITLE
[BUG] totalopenstaion-cli-connector: output file is binary

### ISSUE THREAD

**Issue by enzococca** [steko/totalopenstation#157]
When try to export the file via totalopenstaion-cli-connector.py I have an error . The outputfile should be  binary and not string. So I suggest to change on line 97 

e=open(options.outfile, 'w')
to 
e=open(options.outfile, 'wb')

this works for me

**Comment by steko** [comment]
For reference, also the `totalopenstation-gui.py` script has the same parameter:

https://github.com/totalopenstation/totalopenstation/blob/3fe5346f511b7ec885cdcaebe4d94bfcc5aa95fb/scripts/totalopenstation-gui.py#L783-L784
I think @enzococca told me that the GUI actually works, but it's because the `data` is not what was downloaded but the converted data shown in the text area. Yes, there's a lot of things that need fixing. 
Since we are downloading bytes (binary), we must save bytes to the output file.
